version: '3.8'
services:
  app:
    build:
      context: ./pyAppFolder
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
  web:
    build:
      context: ./nginxFolder
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - app    
  